spring:
   thymeleaf:
      prefix: classpath:WEB-INF/templates/
      check-template-location: true
      mode: HTML5
      suffix: .html
      cache: false
      order: 0
---
spring:
   h2:
      console: 
         enabled: true
         path: /h2-console-test
---
spring:
   datasource:
      url: jdbc:h2:mem:boarder_db;mode=MySQL;INIT=runscript from 'classpath:sql/create_table.sql'
      driver-class-name: org.h2.Driver
      username: sa
---
mybatis:
   type-aliases-package: com.miyam.mBoarder.mapper
   mapper-locations: classpath:mapper/*.xml
---
server:
   port: 8020
---
logging:
   level: 
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}
       - %msg%n"